---
- include: subnetgroup.yml
- include: parametergroup.yml
- include: aws.group_facts.yml
- include: restore.yml
  when: command is defined and command == "restore"
- include: rds.yml
  when: command is defined and command == "create"
- include: replicate.yml
  when: command is defined and command == "replicate"
- include: facts.yml
